### ISSUE TITLE
ESP-IDF Installation Manager (EIM) black screen (VSC-1747)

### ISSUE THREAD

**Issue by SinglWolf** [espressif/vscode-esp-idf-extension#1630]
### OS

Linux

### Operating System version

Operating System: ROSA Fresh Desktop 13 KDE
Plasma Version: 6.4.2
KDE Frameworks Version: 6.15.0
Qt Version: 6.8.3
Kernel Version: 6.12.34-generic-1rosa13-x86_64 (64-bit)
Graphics Platform: X11 
Processors: 4 × Intel® Core™ i3-6100 CPU @ 3.70GHz 
Memory: 8 GiB of RAM (7.6 GiB usable) 
Graphics Processor: Intel® HD Graphics 530

### Description

After launching the EIM, the window flashes after a while, and then turns black.
vscode-esp-idf-extension version 2.0.0
<img width="923" height="760" alt="Image" src="https://github.com/user-attachments/assets/fd825364-b176-4057-8cd6-22df160d9ff9" />

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [x] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by brianignacio5** [comment]
Please post EIM issue in the corresponding repository https://github.com/espressif/idf-im-ui

**Comment by SinglWolf** [comment]
Unfortunately, I have already deleted this application and am using `vscode-esp-idf-extension` v1.10.3.
Moreover, my need to complete an very exciting quest using the specified link to report the problem.
I don't understand how to go through it properly, and I don't have the free time for it.

**Comment by brianignacio5** [comment]
Could you provide the steps you had followed for this ? I can forward to the maintainer of the EIM repository.

**Comment by SinglWolf** [comment]
> Could you provide the steps you had followed for this ? I can forward to the maintainer of the EIM repository.

Thanks!
I was just following the installation instructions. And during the installation process, the `EIM` window started flashing at first, and then turned black. If quickly make the settings, minimized the `EIM` window and after a while can see that the installation is completed. I've been monitoring the activity of the network adapter.

**Comment by brianignacio5** [comment]
It might be related to some linux libraries needed to render the UI. Some Linux distributions have many different packages and hard to support all of them distributions.

**Comment by SinglWolf** [comment]
> It might be related to some linux libraries needed to render the UI. Some Linux distributions have many different packages and hard to support all of them distributions.

I understood. I think it makes sense to add a choice of classic extension settings.

**Comment by brianignacio5** [comment]
As this issue is not related to the extension I'll close this issue.

**Comment by Axa-Ru** [comment]
The same problem on Linux mint 22.2

ESP-IDF Extention 2.01

System:
  Kernel: 6.8.0-87-generic arch: x86_64 bits: 64 compiler: gcc v: 13.3.0 clocksource: tsc
  Desktop: MATE v: 1.26.2 wm: marco v: 1.26.2 with: mate-panel tools: mate-screensaver vt: 7
    dm: LightDM v: 1.30.0 Distro: Linux Mint 22.2 Zara base: Ubuntu 24.04 noble

Graphics:
  Device-1: NVIDIA GK106 [GeForce GTX 660] vendor: Gigabyte driver: nvidia v: 470.256.02
    arch: Kepler pcie: speed: 2.5 GT/s lanes: 16 bus-ID: 01:00.0 chip-ID: 10de:11c0 class-ID: 0300
  Display: x11 server: X.Org v: 21.1.11 with: Xwayland v: 23.2.6 compositor: marco v: 1.26.2
    driver: X: loaded: nvidia unloaded: fbdev,modesetting,nouveau,vesa gpu: nvidia display-ID: :0
    screens: 1


```
$ eim
Running GUI...
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 1200x1000: Permission denied
[2025-11-15][19:48:25][eim::gui::commands::utils_commands][INFO] Set locale to: en
[2025-11-15][19:48:25][eim::gui::commands::utils_commands][INFO] Set locale to: en
axa@amd:$ sudo -i
root@amd:# eim
Running GUI...
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 1200x1000: Permission denied
[2025-11-15][19:48:53][eim::gui::commands::utils_commands][INFO] Set locale to: en
[2025-11-15][19:48:53][eim::gui::commands::utils_commands][INFO] Set locale to: en
```

```
$ sudo cat /sys/module/nvidia_drm/parameters/modeset
Y
```

**Comment by brianignacio5** [comment]
Should be fixed in https://github.com/espressif/vscode-esp-idf-extension/pull/1704

You can test with this [vsix installer](https://nightly.link/espressif/vscode-esp-idf-extension/actions/artifacts/4515532672.zip)

You can test these changes by installing this VSIX by click menu View -> Command Palette..., type Install from VSIX and then select downloaded esp-idf-extension.vsix file to install the extension.

**Comment by g1ra** [comment]
I have the same : 
I installed with : 
```
echo "deb [trusted=yes] https://dl.espressif.com/dl/eim/apt/ stable main" | sudo tee /etc/apt/sources.list.d/espressif.list

apt install eim
```
 ```
Running GUI...

(eim:258609): Gtk-WARNING **: 17:03:26.758: Theme parsing error: gtk.css:3942:55: Using one color stop with linear-gradient() is deprecated.
src/nv_gbm.c:288: GBM-DRV error (nv_gbm_create_device_native): nv_common_gbm_create_device failed (ret=-1)

src/nv_gbm.c:288: GBM-DRV error (nv_gbm_create_device_native): nv_common_gbm_create_device failed (ret=-1)

KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 1200x1000: Permission denied
```

**Comment by peterbaldock** [comment]
This is still a problem with new installations (ESP-IDF V2.02)

System:
  Host: MCC8-002-DI Kernel: 6.8.0-90-generic x86_64 bits: 64
    Desktop: GNOME 42.9 Distro: Ubuntu 22.04.5 LTS (Jammy Jellyfish)
CPU:
  Info: quad core model: Intel Core i3-10105F bits: 64 type: MT MCP cache:
    L2: 1024 KiB
  Speed (MHz): avg: 2575 min/max: 800/4400 cores: 1: 800 2: 4301 3: 800
    4: 4239 5: 4301 6: 4299 7: 1064 8: 800
Graphics:
  Device-1: NVIDIA GK208B [GeForce GT 730] driver: nvidia v: 470.256.02
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: nvidia
    unloaded: fbdev,modesetting,nouveau,vesa gpu: nvidia resolution:
    1: 1920x1080 2: 1920x1080 3: 1920x1080 4: 1920x1080
  OpenGL: renderer: NVIDIA GeForce GT 730/PCIe/SSE2
    v: 4.6.0 NVIDIA 470.256.02


<img width="1220" height="1055" alt="Image" src="https://github.com/user-attachments/assets/41c37a09-7cea-418f-9f23-de62a6fc0773" />
