### ISSUE TITLE
Failed to debug the development board using JTAG (OCD-1274) (VSC-1798)

### ISSUE THREAD

**Issue by sumer274** [espressif/vscode-esp-idf-extension#1709]
### Development Kit

ESP32-C5-DevKitC-1

### Module or chip used

ESP32-C5-WROOM-1

### Debug Adapter

Chip on-board JTAG debugger

### OpenOCD version

v0.12.0-esp32-20250707

### Operating System

windows

### Using an IDE ?

VScode

### OpenOCD command line

riscv32-esp-elf-gdb -q -x build/gdbinit/symbols -x build/gdbinit/prefix_map -x build/gdbinit/connect build/hello_world.elf

### JTAG Clock Speed

Default

### ESP-IDF version

v5.5.1

### Problem Description

I first tried debugging routines in the VSCODE IDE, and was able to successfully burn the program to the Development Board via the USB interface, while the opencd seemed to be able to communicate with the development board normally to get information about the development board, i was able to monitor the execution of the program through the monitor, but I couldn't start debugging properly; then I tried to start GDB debugging by following the steps of the debugging tutorial on the website, and the results are as shown in the logs below:

### Debug Logs

```shell
PS C:\Users\lqh\Desktop\hello_world> openocd -f board/esp32c5-builtin.cfg                                                                    
Open On-Chip Debugger v0.12.0-esp32-20250707 (2025-07-06-17:44)                                                                              
Licensed under GNU GPL v2                                                                                                                    
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
Info : esp_usb_jtag: VID set to 0x303a and PID to 0x1001
Info : esp_usb_jtag: capabilities descriptor set to 0x2000
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Info : esp_usb_jtag: serial (3C:DC:75:82:1E:CC)
Info : esp_usb_jtag: Device found. Base speed 24000KHz, div range 1 to 255
Info : clock speed 24000 kHz
Info : JTAG tap: esp32c5.tap0 tap/device found: 0x00017c25 (mfg: 0x612 (Espressif Systems), part: 0x0017, ver: 0x0)
Info : JTAG tap: esp32c5.tap1 tap/device found: 0x00017c25 (mfg: 0x612 (Espressif Systems), part: 0x0017, ver: 0x0)
Info : [esp32c5] datacount=1 progbufsize=2
Info : [esp32c5] Examined RISC-V core; found 1 harts
Info : [esp32c5]  XLEN=32, misa=0x40103105
Info : [esp32c5] Examination succeed
Info : [esp32c5] starting gdb server on 3333
Info : Listening on port 3333 for gdb connections
shutdown command invoked
PS C:\Users\lqh\Desktop\hello_world> riscv32-esp-elf-gdb -q -x build/gdbinit/symbols -x build/gdbinit/prefix_map -x build/gdbinit/connect build/hello_world.elf
Reading symbols from build/hello_world.elf...
add symbol table from file "C:/Users/lqh/Desktop/hello_world/build/bootloader/bootloader.elf"
warning: could not convert 'main' from the host encoding (CP1252) to UTF-32.
This normally should not happen, please file a bug report.
build/gdbinit/connect:3: Error in sourced command file:
could not connect (error 138):
```

### Expected behavior

NULL

### Screenshots

<img width="1277" height="501" alt="Image" src="https://github.com/user-attachments/assets/8a1da655-a357-4a4c-8cbb-a984fdfb2eeb" />

<img width="1273" height="478" alt="Image" src="https://github.com/user-attachments/assets/c7bd0144-6145-4046-9364-9d3b24f249ca" />

<img width="453" height="230" alt="Image" src="https://github.com/user-attachments/assets/956763ca-17c6-47b8-9244-d651f8d186d2" />

<img width="1286" height="463" alt="Image" src="https://github.com/user-attachments/assets/1d2b3cac-91eb-4016-8fad-d5ad6cf4ee71" />

**Comment by erhankur** [comment]
I don't see an issue when I try from cmd line without IDE. _warning:_ could not convert 'main' from the host encoding (CP1252) to UTF-32.  does not break the communication. 

Maybe @brianignacio5 (IDE team) might help.

**Comment by sumer274** [comment]
build/gdbinit/connect:3: Error in sourced command file:
could not connect (error 138):
Doesn't this output affect the GDB debugging process？

**Comment by erhankur** [comment]
Could you try from command line? Inside hello_world example, `idf.py openocd gdb`

**Comment by sumer274** [comment]
> Could you try from command line? Inside hello_world example, `idf.py openocd gdb`你能试试命令行吗？在 hello_world 例子中，`idf.py openocd gdb`

I tried it and found that gdb can be run for debugging in command-line mode; But I may rely more on using IDE (VSCode) for debugging. How can I seek help for issues where I cannot debug in IDE

**Comment by erhankur** [comment]
cc @brianignacio5

**Comment by brianignacio5** [comment]
Hi @sumer274 @erhankur 

Please could you open a GitHub issue in the [ESP-IDF extension for VS Code](https://github.com/espressif/vscode-esp-idf-extension/issues/new/choose) repository ? The current screenshots do not provide me information of why the debug session is not working. The Perl language server is not related to this.

We need to see the `ESP-IDF` output related to OpenOCD as described in [troubleshooting docs](https://docs.espressif.com/projects/vscode-esp-idf-extension/en/latest/troubleshooting.html). 

You can also try using our [latest master build](https://nightly.link/espressif/vscode-esp-idf-extension/workflows/ci/master/esp-idf-extension.vsix.zip) You can use this VSIX by pressing `F1` or click menu `View` -> `Command Palette...`, type `Install from VSIX` and then select the previously downloaded .vsix file to install the extension.

**Comment by brianignacio5** [comment]
I think this issue should be fixed with #1652 

Please try the latest master @sumer274  as I described in the previous comment.

**Comment by sumer274** [comment]
> Hi [@sumer274](https://github.com/sumer274) [@erhankur](https://github.com/erhankur)
> 
> Please could you open a GitHub issue in the [ESP-IDF extension for VS Code](https://github.com/espressif/vscode-esp-idf-extension/issues/new/choose) repository ? The current screenshots do not provide me information of why the debug session is not working. The Perl language server is not related to this.
> 
> We need to see the `ESP-IDF` output related to OpenOCD as described in [troubleshooting docs](https://docs.espressif.com/projects/vscode-esp-idf-extension/en/latest/troubleshooting.html).
> 
> You can also try using our [latest master build](https://nightly.link/espressif/vscode-esp-idf-extension/workflows/ci/master/esp-idf-extension.vsix.zip) You can use this VSIX by pressing `F1` or click menu `View` -> `Command Palette...`, type `Install from VSIX` and then select the previously downloaded .vsix file to install the extension.

OK, I'll start an issue in ESP-IDF extension for VS Code.I need to clarify a few cases, and before I try to find some workarounds in the issue in ESP-IDF extension for VS Code, I'm relying on the debug console output: set remote hardware-watchpoint-limit undefined. A launch.json was found in a reply. The contents of the launch.json file:

<img width="838" height="465" alt="Image" src="https://github.com/user-attachments/assets/b0043c3c-16c2-40c2-baa9-5fb9bc02495b" />I saw the definition of hardware-watchpoint in it, and I tried it in my launch. Add the following field to the launch.json file:

<img width="678" height="507" alt="Image" src="https://github.com/user-attachments/assets/283d5a51-d2d0-43b1-96d6-77246ba5b14b" />Then I tried debugging again and found that I could start debugging in the IDE. But the debugging process didn't go as planned. According to the ESPRESSIF documentation, the program should stop at app_main() after debugging starts, but it didn't, and I tried to add breakpoints in some code, but the program did not stop at the breakpoint as expected.

**Comment by brianignacio5** [comment]
HI @sumer274  the behaviour you described is fixed in master already.

The reason why is not stopping when you manually setting initCommands? Is because you need to add `thb app_main` in initCommands too which is done by default by extension and idf.py gdb but when you set it manually you need to specify it.

**Comment by FireDeveloper** [comment]
I had the same issue. Just installing release from master didn't fix the issue.
I had to also remove IDF and tools and reinstall them too (5.5.1) and I can debug on C5.

Update: After a day of trying it, its all over the place. Sometimes it works, sometimes displays the error about CP1252.
Unfortunately C5 is not yet an option in Eclipse IDE.

**It's the first time I use internal USB JTAG and VSCode debug, I may do things wrong, but it's an awful experience so far.
There is always a popup about OCD not running, I had to close and reopen VSCode a couple times because it wasn't working. I am not sure if debug also flashes the firmware, I guess not, and I am not sure how to configure it that way...

**Comment by brianignacio5** [comment]
@FireDeveloper I'm sorry you are facing these issues. Could you share with us the OpenOCD output when it is not working? The behavior from @sumer274 should be solved already in master. Is there a different kind of error? Did you also modified the initCommands in launch.json ?

**Comment by FireDeveloper** [comment]
I didn't modify something. Only pulled the latest vsix from your link, and reinstalled IDF (via VSCode wizard)
The day after my previous post, I only used JTAG for flashing. It went smoother, but occasionally the JTAG refused to connect.
My device was in a boot loop when this happened, so I guess it may had difficulties to connect while rebooting.

I will post the output the next time I get it.

**Comment by FireDeveloper** [comment]
Today I tried to continue from where I was left off.
It looks like the device is being flashed correctly, but debug doesn't work.

Debug console:
```
Debug adapter -> Extension: DEBUG_ADAPTER_STARTED
Debug adapter -> Extension: DEBUG_ADAPTER_READY2CONNECT
Debug Adapter initialized
Debug Adapter is running
Failed to get backtrace! (error / {'msg': 'Remote connection closed'})
'DebuggerError' object is not iterable
```

Output:
```
Open On-Chip Debugger v0.12.0-esp32-20250707 (2025-07-06-17:44)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html

debug_level: 2

Info : esp_usb_jtag: VID set to 0x303a and P
ID to 0x1001
Info : esp_usb_jtag: capabilities descriptor set to 0x2000

Info : Listening on port 6666 for
 tcl connections
Info : Listening on port 4444 for telnet connections

Info : esp_usb_jtag: serial (3C:DC:75:83:B6:74
)

Info : esp_usb_jtag: Device found. Base speed 24000KHz, div range 1 to 255

Info : clock speed 
24000 kHz

Info : JTAG tap: esp32c5.tap0 tap/device found: 0x00017c25 (mfg: 0x612 (Espressif Systems), part: 0x0017, ver: 0x0)
Info : JTAG tap: esp32c5.tap1 tap/device found: 0x00017c25 (mfg: 0x612 (Espressif Systems), part: 0x0017, ver: 0x0)

Info : [esp32c5] datacount=1 progbufsize=
2

Info : [esp32c5] Examined RISC-V core; found 1 harts

Info : [esp32c5]  XLEN=32, misa=0x40103105
Info : [esp32c5] Examination succeed
Info : [esp32c5] starting gdb server on 3333
Info : Listening on port 3333 for gdb connections

[/OpenOCD]
[Debug Adapter]
DEBUG_ADAPTER_STARTED
2025-12-07 17:27:13,229 - Debug Adapter (main) - CRITICAL - Debug adapter -> Extension: DEBUG_ADAPTER_STARTED

DEBUG_ADAPTER_READY2CONNECT
2025-12-07 17:27:13,233 - Debug Adapter (main) - CRITICAL - Debug adapter -> Extension: DEBUG_ADAPTER_READY2CONNECT

[/Debug Adapter]
[OpenOCD]
Info : accepting 'gdb' connection on tcp/3333

Info : [esp32c5] Target halted, PC=0x40808
0EC, debug_reason=00000000

Warn : No symbols for FreeRTOS!

Warn : [esp32c5] Failed to read m
emory via program buffer.

Info : [esp32c5] Found 3 triggers

Info : Flash mapping 0: 0x10020 -> 0x420c0020
, 134 KB
Info : Flash mapping 1: 0x40020 -> 0x42000020, 728 KB
Info : Auto-detected flash bank 'esp32c5.flash' size 16384 KB
Info : Using flash bank 'esp32c5.flash' size 16384 KB

Info : Flash mapping 0: 0x10020 -> 0x420c0020,
 134 KB
Info : Flash mapping 1: 0x40020 -> 0x42000020, 728 KB
Info : Using flash bank 'esp32c5.irom' size 732 KB

Info : Flash mapping 0: 0x10020 -> 0x42
0c0020, 134 KB
Info : Flash mapping 1: 0x40020 -> 0x42000020, 728 KB
Info : Using flash bank 'esp32c5.drom' size 136 KB

Warn : Prefer GDB command "target extended-r
emote :3333" instead of "target remote :3333"

Memory Map (8 regions):
----------------------------------------
Type    Start Addr    Length    BlockSize
----------------------------------------
FLASH   0x00000000  0x01000000  0x00001000
R/W     0x01000000  0x3f000000  0x00000000
ROM     0x40000000  0x00050000  0x00000000
R/W     0x40050000  0x01fb0000  0x00000000
FLASH   0x42000000  0x000b7000  0x00001000
R/W     0x420b
7000  0x00009000  0x00000000
FLASH   0x420c0000  0x00022000  0x00001000
R/W     0x420e2000  0xbdf1e000  0x00000000
----------------------------------------

Info : Detected FreeRTOS version: (10.5.1)

Info : JTAG tap: esp32c5.tap0 tap/device fo
und: 0x00017c25 (mfg: 0x612 (Espressif Systems), part: 0x0017, ver: 0x0)
Info : JTAG tap: esp32c5.tap1 tap/device found: 0x00017c25 (mfg: 0x612 (Espressif Systems), part: 0x0017, ver: 0x0)

Info : [esp32c5] Reset cause (24) - (JTAG CPU reset)

Info : Flash mapping 0: 0x10020 -> 0x420c0020, 134 KB

Info : Flash mapping 1: 0x40020 -> 0x42000020, 728 KB
Info : Using flash bank 'esp32c5.irom' size 732 KB

Info : Flash mapping 0: 0x10020 -> 0x420c0020, 134 KB

Info : Flash mapping 1: 0x40020 -> 0x42000020, 728 KB
Info : Using flash bank 'esp32c5.drom' size 136 KB

Info : Flash mapping 0: 0x10020 -> 0x420c
0020, 134 KB
Info : Flash mapping 1: 0x40020 -> 0x42000020, 728 KB
Info : Auto-detected flash bank 'esp32c5.flash' size 16384 KB
Info : Using flash bank 'esp32c5.flash' size 16384 KB

Info : dropped 'gdb' connection

Info : accepting 'gdb' connection on tcp/3333

Info : [esp32c5] Target halted, PC=0x40001610, debug_reason=00000001

Info : Detected Fr
eeRTOS version: (10.5.1)

Memory Map (8 regi
ons):
----------------------------------------
Type    Start Addr    Length    BlockSize
----------------------------------------
FLASH   0x00000000  0x01000000  0x00001000
R/W     0x01000000  0x3f000000  0x00000000
ROM     0x40000000  0x00050000  0x00000000
R/W     0x40050000  0x01fb0000  0x00000000
FLASH   0x42000000  0x000b7000  0x00001000
R/W     0x420b7000  0x00009000  0x00000000
FLASH   0x420c0000  0x00022000  0x00001000
R/W     0x420e2000  0xbdf1e000  0x00000000
----------------------------------------

Info : [esp32c5] Target halted, PC=0x4200BB64, debug_reason=00000001

❌ Error: gdb requested a non-existing register (reg_num=73)
Error: gdb requested a non-existing register (reg_num=73)

Info : dropped 'gdb' connection

Info : [esp32c5] Hart unexpectedly reset!

Info : [esp32c5] Reset caus
e (21) - (USB (UART) core reset)

```

launch.json
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "gdbtarget",
      "request": "attach",
      "name": "Eclipse CDT GDB Adapter"
    },
    {
      "type": "espidf",
      "name": "Launch",
      "request": "launch"
    }
  ]
}
```
settings.json
```
{
  "C_Cpp.intelliSenseEngine": "default",
  "idf.espIdfPathWin": "c:\\Espressif\\v5.5.1\\esp-idf",
  "idf.pythonInstallPath": "C:\\Espressif\\Tools\\tools\\idf-python\\3.11.2\\python.exe",
  "idf.openOcdConfigs": [
    "board/esp32c5-builtin.cfg"
  ],
  "idf.portWin": "COM9",
  "idf.toolsPathWin": "C:\\Espressif\\Tools",
  "idf.customExtraVars": {
    "OPENOCD_SCRIPTS": "C:\\Espressif\\tools\\openocd-esp32\\v0.12.0-esp32-20230921/openocd-esp32/share/openocd/scripts",
    "IDF_CCACHE_ENABLE": "1",
    "ESP_ROM_ELF_DIR": "C:\\Espressif\\tools\\esp-rom-elfs\\20230320/",
    "IDF_TARGET": "esp32c5"
  },
  "clangd.path": "C:\\Espressif\\Tools\\tools\\esp-clang\\esp-19.1.2_20250312\\esp-clang\\bin\\clangd.exe",
  "clangd.arguments": [
    "--background-index",
    "--query-driver=**",
    "--compile-commands-dir=f:\\_Projects\\485_Link\\mcu\\link_485\\build"
  ],
  "idf.flashType": "JTAG"
}
```
c_cpp_properties.json
```
{
  "configurations": [
    {
      "name": "ESP-IDF",
      "compilerPath": "${config:idf.toolsPathWin}\\tools\\riscv32-esp-elf\\esp-14.2.0_20241119\\riscv32-esp-elf\\bin\\riscv32-esp-elf-gcc.exe",
      "compileCommands": "${config:idf.buildPath}/compile_commands.json",
      "includePath": [
        "${config:idf.espIdfPath}/components/**",
        "${config:idf.espIdfPathWin}/components/**",
        "${workspaceFolder}/**"
      ],
      "browse": {
        "path": [
          "${config:idf.espIdfPath}/components",
          "${config:idf.espIdfPathWin}/components",
          "${workspaceFolder}"
        ],
        "limitSymbolsToIncludedHeaders": true
      }
    }
  ],
  "version": 4
}
```

**Comment by erhankur** [comment]
@FireDeveloper could you check hw revision of your devkit? You can see it in the bootlog. 
```
ESP-ROM:esp32c5-eco2-20250121
Build:Jan 21 2025
```

From the [latest](https://github.com/espressif/openocd-esp32/releases/tag/v0.12.0-esp32-20250707) OpenOCD release note

> ESP32-C5 — CSRs have been aligned with the ECO2 specification for stable debugging (use earlier OpenOCD versions with pre-ECO2 hardware).

**Comment by FireDeveloper** [comment]
```
ESP-ROM:esp32c5-eco2-20250121
Build:Jan 21 2025
rst:0x15 (USB_UART_HPSYS),boot:0x3e (SPI_FAST_FLASH_BOOT)
Core0 Saved PC:0x408080da
SPI mode:DIO, clock div:1
load:0x408556b0,len:0x1710
load:0x4084bba0,len:0xd9c
load:0x4084e5a0,len:0x3198
entry 0x4084bbaa
I (23) boot: ESP-IDF v5.5.1 2nd stage bootloader
I (23) boot: compile time Nov 30 2025 14:47:36
I (24) boot: chip revision: v1.0
I (25) boot: efuse block revision: v0.3
I (27) boot.esp32c5: SPI Speed      : 80MHz
I (31) boot.esp32c5: SPI Mode       : DIO
I (34) boot.esp32c5: SPI Flash Size : 16MB
```

I deleted the build folder manually and built the project again, without any change.
Reflashed the device and now debug works and stops in app_main

**Comment by brianignacio5** [comment]
Closing this issue as it seems to be solved in master.

Comment here if you need more assistance.
